service: base-aws-bot-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${env:stage}
  iamRoleStatements:
      -
        Effect: 'Allow'
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          'Fn::GetAtt': ['UsersTable', 'Arn']
      - Effect: Allow
        Action:
          - logs:*
        Resource:
          - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:logs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - '*'
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    REGION: us-east-1
    USER_TABLE: ${self:custom.user_table}
    BOT_NAME: ${self:custom.bot_name}
    MAIN_LOG_GROUP: /aws/lambda/base-aws-bot-bot-${env:stage}-main

package:
 patterns:
  - '!./**'
  - app/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
  user_table: ${env:stage}_base-aws-bot-bot_users_table
  bot_name: ${env:stage}_base-aws-bot-bot

plugins:
  - serverless-python-requirements
  - serverless-step-functions

functions:
  main:
    handler: app/main.main
    url: true
  calculate_report_data:
    handler: app/reporting.calculate_data
  send_report:
    handler: app/reporting.main

stepFunctions:
  stateMachines:
    ${file(resources/report_step_function/index.yml)}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.user_table}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1